### ISSUE TITLE
Syntax highlighting not working correctly

### ISSUE THREAD

**Issue by ddevaal** [BrendanThompson/terraform-nova#3]
For as long as I can remember the syntax highlighting that this extension provides is not working correctly: 

![Nova](https://github.com/BrendanThompson/terraform-nova/assets/74067645/1d3b4a1a-2c85-4eb6-8d18-fe0738cbe701)

Everything after the Helm resource is just grey. It also happens with the HCL extension. Also can we expect provider completions or is it a terraform-ls thing? I'm really sad that my favourite editor doesn't support this out of the box (vscode works fine).

**Comment by BrendanThompson** [comment]
@ddevaal any chance you could pop that in a code snippet for me and I will have a look?

**Comment by ddevaal** [comment]
> @ddevaal any chance you could pop that in a code snippet for me and I will have a look?

Sorry for the late reply. TextMate 2 has the same problem. Coincidence? I'm not sure why Nova is not using Treesitter for HCL/TF files. It's hard to find a good 'Mac-assed' text editor nowadays.

```
resource "helm_release" "helm_release" {
  name         = "argo-cd"

  set {
    name  = "crds.install"
    value = "false"
  }

  values = [
    <<-EOF
    server:
      rbacConfig:
        policy.csv: |
          p, role:om-admin, applications, get, *-teams/*-om-*, allow
    configs:
      secret:
        createSecret: true
        extra:
          oidc.azure.clientSecret: "${azuread_application_password.application_password.value}"
    EOF
  ]

  depends_on = [kubectl_manifest.kubectl_manifest]
}
```

**Comment by BrendanThompson** [comment]
@ddevaal it looks like the culprit is `*-teams/*-om-*` as `/*` is the start of a multiline comment block. So technically this behaviour is what we _would_ expect.

In terms of tree-sitter, I would expect the same result to be honest. This plugin currently uses the language server for everything, as well as some baseline using the `XML` Nova language syntax definition. I have looked at adding tree-sitter however the LS should realistically provide everything required.

As for what we can do to fix this, at this stage I am not sure there is anything that would resolve this problem. We might need to raise a bug in the `terraform-ls` repository, however I expect the behaviour is desired.

**Comment by ddevaal** [comment]
> @ddevaal it looks like the culprit is `*-teams/*-om-*` as `/*` is the start of a multiline comment block. So technically this behaviour is what we _would_ expect.

I'm sorry but I think you're wrong here. It's inside a heredoc. It should color the whole heredoc block, but nothing else.

> 
> In terms of tree-sitter, I would expect the same result to be honest. 

Heredocs are fully supported in most editors/IDE's (including those that use treesitter). I know because I have tested all of them. Zed, Neovim, Helix, you name it. It's also not a problem in vscode or JetBrains products.

>This plugin currently uses the language server for everything, as well as some baseline using the `XML` Nova language >syntax definition. I have looked at adding tree-sitter however the LS should realistically provide everything required.
 
> As for what we can do to fix this, at this stage I am not sure there is anything that would resolve this problem. We might need to raise a bug in the `terraform-ls` repository, however I expect the behaviour is desired.

I highly doubt that it's a bug in terraform-ls. Neovim or Helix and other editors that I've tested use the same language server. Maybe the problem is in the XML syntax definitions included with this extension?

Neovim below (LazyVim):

<img width="795" alt="Scherm­afbeelding 2024-02-25 om 23 06 57" src="https://github.com/BrendanThompson/terraform-nova/assets/74067645/4988fc24-4943-4f40-9619-fead538bbd48">

**Comment by BrendanThompson** [comment]
@ddevaal you are absolutely 100% correct, my bad! Looked into it, so I was wrong, the LSP isn't providing syntax highlighting at all it's all don by the Nova language definition. It actually works completely fine except in one scenario -that we've found- where the `heredoc` is within an array/list. Pushing a release for it now.

**Comment by ddevaal** [comment]
> @ddevaal you are absolutely 100% correct, my bad! Looked into it, so I was wrong, the LSP isn't providing syntax highlighting at all it's all don by the Nova language definition. It actually works completely fine except in one scenario -that we've found- where the `heredoc` is within an array/list. Pushing a release for it now.

I read on the Nova dev forum that they will transition to Treesitter in the future. Not sure what that means for this extension. Anyways, Thanks for finding and fixing the issue! 🎉🚀

**Comment by BrendanThompson** [comment]
No problems, yeah I've started looking into the tree-sitter stuff today too. It'll take me a while to wrap my head around though haha!!
